### ISSUE TITLE
No logs in gen_dataVals

### ISSUE THREAD

**Issue by cwnaber** [carrien/free-speech#106]
`gen_dataVals_from_wave_viewer` should include more metadata. Specifically:
* what input settings were used to run it,
* when it was run, 
* who ran it, 
* etc.?

This would improve troubleshooting and investigation after a dataVals of unknown provenance is used.

We should probably do the same for variants of gen_dataVals_from_wave_viewer

**Comment by carrien** [comment]
Agreed, with the most important being what settings were used (not just inputs, but also other parameters set by the logic of the function). Not sure we need to worry about variants since I think they're all experiment-specific, and we're moving towards not needing to use variants with the multiple cases covered by gen_dataVals_from_wave_viewer.

**Comment by cwnaber** [comment]
Notes from talking to carrie today.

Fields to include in log:
* dataPath
* trialdir
* bMultisegment
* eventMode
* vowel_list
* date (via `date`, the same method used in `set_exptDefaults`)

For variables that don't always get set (such as eventMode), use `[]` if it isn't set by the function.

Save the results in another variable called `dataVals_params`. When the file `dataVals.mat` gets saved, it can include the variables `dataVals` and `dataVals_params`.

For the "variants," eg gen_dataVals_timeAdapt, we do not plan to make this change, since they are rarely used. As a separate issue, many of the variants can be moved to their respective folder in the current-studies repo, if one exists.

NEXT STEPS: Chris will code up changes and send for review.

**Comment by cwnaber** [comment]
Fixed in #110
